fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        exclude: (^|/)migrations/
      - id: mixed-line-ending
        exclude: (^|/)migrations/
      - id: trailing-whitespace
        exclude: (^|/)migrations/
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with rustfmt.
        entry: cargo +nightly fmt --all -- --check
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-deny
        name: cargo deny check
        description: Check cargo dependencies
        entry: cargo deny check
        language: system
        files: \.rs$
        pass_filenames: false
      - id: typos
        name: typos
        description: check typo
        entry: typos
        language: system
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check --workspace --all-features
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Lint rust sources
        entry: cargo clippy --workspace --all-targets --all-features -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        description: unit test for the project
        entry: cargo nextest run --all-features --workspace --no-tests=pass
        language: system
        files: \.rs$
        pass_filenames: false
      - id: changelog
        name: update changelog
        description: Update CHANGELOG.md with unreleased changes
        entry: bash -c 'git cliff -o CHANGELOG.md && git add CHANGELOG.md'
        language: system
        pass_filenames: false
        stages: [pre-commit]
